export const ErrorCodes = {
  // General / Common
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INVALID_REQUEST: "INVALID_REQUEST",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  OPERATION_FAILED: "OPERATION_FAILED",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Networks
  INVALID_NETWORK: "INVALID_NETWORK",

  // Authentication
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_ACCOUNT_DISABLED: "USER_ACCOUNT_DISABLED",
  USER_PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED",

  // API Key Management
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  API_KEY_MISSING: "API_KEY_MISSING",
  API_KEY_INVALID: "API_KEY_INVALID",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  API_KEY_ACCESS_DENIED: "API_KEY_ACCESS_DENIED",
  API_KEY_CREATION_FAILED: "API_KEY_CREATION_FAILED",
  API_KEY_SPENDING_LIMIT_REACHED: "API_KEY_SPENDING_LIMIT_REACHED",
  API_KEY_DELETE_FAILED: "API_KEY_DELETE_FAILED",
  API_KEY_RATE_LIMIT_EXCEEDED: "API_KEY_RATE_LIMIT_EXCEEDED",

  // Authorization / Permission
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ROLE_NOT_ALLOWED: "ROLE_NOT_ALLOWED",
  RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_INPUT_VALUE: "INVALID_INPUT_VALUE",

  // Database / Prisma
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED: "DATABASE_QUERY_FAILED",
  DUPLICATE_RECORD: "DUPLICATE_RECORD",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",

  // Billing / Payment
  BILLING_INSUFFICIENT_BALANCE: "BILLING_INSUFFICIENT_BALANCE",
  BILLING_PAYMENT_FAILED: "BILLING_PAYMENT_FAILED",
  BILLING_TRANSACTION_FAILED: "BILLING_TRANSACTION_FAILED",
  BILLING_TRANSACTION_NOT_FOUND: "BILLING_TRANSACTION_NOT_FOUND",
  BILLING_REFUND_FAILED: "BILLING_REFUND_FAILED",
  BILLING_INVALID_AMOUNT: "BILLING_INVALID_AMOUNT",

  // Balance
  BALANCE_NOT_FOUND: "BALANCE_NOT_FOUND",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  PRICING_EXPIRED: "PRICING_EXPIRED",

  // Wallet / Blockchain
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_CONNECTION_FAILED: "WALLET_CONNECTION_FAILED",
  WALLET_INVALID_ADDRESS: "WALLET_INVALID_ADDRESS",
  WALLET_TRANSACTION_FAILED: "WALLET_TRANSACTION_FAILED",
  WALLET_INSUFFICIENT_FUNDS: "WALLET_INSUFFICIENT_FUNDS",
  WALLET_SIGNATURE_FAILED: "WALLET_SIGNATURE_FAILED",

  //Circle
  CIRCLE_TRANSACTION_FAILED: "CIRCLE_TRANSACTION_FAILED",
  CIRCLE_WALLET_SET_NOT_CONFIGURED: "CIRCLE_WALLET_SET_NOT_CONFIGURED",
  CIRCLE_WALLET_CREATION_FAILED: "CIRCLE_WALLET_CREATION_FAILED",
  CIRCLE_INVALID_WEBHOOK: "CIRCLE_INVALID_WEBHOOK",

  // AI / Model Provider
  AI_MODEL_NOT_FOUND: "AI_MODEL_NOT_FOUND",
  AI_MODEL_NOT_AVAILABLE: "AI_MODEL_NOT_AVAILABLE",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_PROVIDER_TIMEOUT: "AI_PROVIDER_TIMEOUT",
  AI_REQUEST_FAILED: "AI_REQUEST_FAILED",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",
  AI_RESPONSE_INVALID: "AI_RESPONSE_INVALID",
  AI_MODEL_PRICING_EXPIRED: "AI_MODEL_PRICING_EXPIRED",
  NOT_FOUND: "NOT_FOUND",

  // Webhook
  WEBHOOK_INVALID_SIGNATURE: "WEBHOOK_INVALID_SIGNATURE",
  WEBHOOK_PROCESSING_FAILED: "WEBHOOK_PROCESSING_FAILED",
  WEBHOOK_ALREADY_PROCESSED: "WEBHOOK_ALREADY_PROCESSED",
  WEBHOOK_PROVIDER_ERROR: "WEBHOOK_PROVIDER_ERROR",
  WEBHOOK_SIGNATURE_MISSING: "WEBHOOK_SIGNATURE_MISSING",
  WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",

  // External Services
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  EXTERNAL_API_FAILED: "EXTERNAL_API_FAILED",
  EXTERNAL_API_TIMEOUT: "EXTERNAL_API_TIMEOUT",

  // File / Upload
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",

  // Creator
  CREATOR_ALREADY_EXISTS: "CREATOR_ALREADY_EXISTS",
  CREATOR_PROFILE_NOT_FOUND: "CREATOR_PROFILE_NOT_FOUND",
  CREATOR_ACCESS_REQUIRED: "CREATOR_ACCESS_REQUIRED",

  // api listing
  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
  SSRF_BLOCKED: "SSRF_BLOCKED",
  API_NOT_FOUND: "API_NOT_FOUND",

  // consumer
  ALREADY_SUBSCRIBED: "ALREADY_SUBSCRIBED",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",

  // Notification
  NOTIFICATION_SEND_FAILED: "NOTIFICATION_SEND_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  // Security
  SECURITY_VIOLATION: "SECURITY_VIOLATION",
  SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
